### ISSUE TITLE
Separate src and trg language selection

### ISSUE THREAD

**Issue by martinpopel** [ufal/lindat_translation#7]
With the growing number of translation directions (few more may be added in few months) it is more obvious we need the "standard" UI,
i.e. one drop-down for the source language selection and another for the target language (similar to Google Translate, Microsoft Bing Translator, etc).

This is related also to #3 pivot translation, which will increase the number of translation directions.

Optionally:
After selecting the source language, some languages in the target-language menu may be absent or grayed out if not available.
We can also distinguish with colors a direct vs. pivot translation (although neither Google nor Microsoft provide this distinction and it seems the users don't need to know this).

**Comment by stranak** [comment]
> Optionally:
After selecting the source language, some languages in the target-language menu may be absent or grayed out if not available.

I would say this is not optional.

**Comment by kosarko** [comment]
the src and tgt languages were separated as part of #13
